BEGIN TRANSACTION;
CREATE TABLE `PEER_FILE` (
	`PEERID`	INTEGER NOT NULL,
	`FILEID`	INTEGER NOT NULL
);
);
CREATE TABLE `PEERS` (
	`PEERID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`MACADD`	INTEGER NOT NULL,
	`STATUS`	INTEGER,
	`LASTCONNECTED`	TEXT,
	`UPTIME`	INTEGER NOT NULL
);
);
CREATE TABLE `FILE_MAP` (
	`FOLDER_FILEID`	INTEGER NOT NULL,
	`FILE_FILEID`	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY(FILE_FILEID)
);
);
CREATE TABLE `FILES_N_FOLDERS` (
	`FILEID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FILENAME`	TEXT NOT NULL,
	`FILESIZE`	INTEGER NOT NULL,
	`CREATIONTIME`	TEXT NOT NULL,
	`LASTMODIFIED`	TEXT NOT NULL,
	`FILEPATH`	TEXT NOT NULL UNIQUE,
	`ISFOLDER`	INTEGER NOT NULL DEFAULT 0
);
);
COMMIT;
